### ISSUE TITLE
'VirtualAloc Remapping Failed' error

### ISSUE THREAD

**Issue by Stryxus** [rumangerst/CSLMusicMod#11]
Output Log: [http://pastebin.com/nH1Fmjby](http://pastebin.com/nH1Fmjby)
Error Log: Wont be of use due to its just full of byte arrays

**Comment by rumangerst** [comment]
Very strange. For some reason you hit some kind of memory limit (it fails to load assets at the very end). CSL Music Mod will load some textures (for the panels and the radio icons; but they are only very small), so it just could be the extra bit needed to crash your game.

How much RAM do you have? What OS? x86 or x64?

**Comment by Stryxus** [comment]
I have 16GB of RAM on Windows 10 Pro 64 bit, i did test this and it only goes up to 10gb (which is normal due to the amount of building assets) then it throws the error.

Could be that Unity has a hard coded RAM usage limit? not sure.

**Comment by rumangerst** [comment]
Unfortunately I don't have enough knowledge about Unity and how it manages its memory. By googling for your error it seems that it may be caused by certain assets (some cloverleaf intersections). They wrote that finding and removing those fixed the problems.

**Comment by Stryxus** [comment]
Solved it, apparently it was nothing to do with the mod but how Unity allocates texture memory for assets, it seems if you go over 4gb it starts using the page file and of course, i disabled it because i have 6gb of VRAM
