### ISSUE TITLE
( CSL mod working nicely ; directory of music files? )

### ISSUE THREAD

**Issue by Ron918** [rumangerst/CSLMusicMod#28]
Thanks for the great mod! Favorite!
It's working nicely! :)

Maybe I'm wrong to ask here :) the following:
I can't find the music-files in the listed directories:

I have 10 music packs installed, working ingame.
But actually there are no files in the directories described in the manuals (create radio channel, music pack) :

\Steam\steamapps\common\Cities_Skylines\CSLMusicMod_Music

%LOCALAPPDATA%\Colossal Order\Cities_Skylines\Addons\Mods\ "e.g." My_Epic_Music\CSLMusicMod_Music

**Comment by rumangerst** [comment]
Music pack mods have a separate CSLMusicMod_Music folder that is located within the workshop item directory.
Steam workshop puts its files into \Steam\steamapps\workshop\content\ and then under a directory for the game and a directory for each installed workshop item.
