### ISSUE TITLE
Cannot create radio station

### ISSUE THREAD

**Issue by zenius11** [rumangerst/CSLMusicMod#7]
I feel like it's an obvious problem but the radio station doesn't show up in the Radio drop-down menu. What am I doing wrong? 

1. All music I'm using does show up in CSLMusic Mix just fine.
2. Code:
  > {
  >  "name" : "RadioEDM",
  >  "collections" : ["EDM Day", "EDM Night"],
  >  "thumbnail" : "img.png",
  >   "schedule" : [
  >      { "type" : "music", "min" : 1, "max" : 3 },
  >     { "type" : "blurb", "min" : 1, "max" : 1 },
  >	{ "type" : "commercial", "min" : 1, "max" : 1 },
  >	{ "type" : "blurb", "min" : 1, "max" : 1 },
  >      { "type" : "music", "min" : 1, "max" : 2 }
  >  ]
  >	"contexts" : [
  >      { "conditions" : [ [ { "type" : "time", "from" : 6, "to" : 19 } ] ], "collections" : ["EDM Day"]},
  >      { "conditions" : [ [ { "type" : "time", "from" : 19, "to" : 6 } ] ], "collections" : ["EDM Night"]}
  >  ]
   > } `
3. Placed JSON file under **C:\Program Files (x86)\Steam\SteamApps\common\Cities_Skylines\CSLMusicMod_Music**
Both "EDM Day" and "EDM Night" folders are located where the JSON file is. Ditto for "**img.png**"
4. I've properly put "#blurb" and "#commercial" for their respective .ogg files in both collections.

**Comment by rumangerst** [comment]
I think it's just invalid JSON. Have you tried services like jsonlint.com to check if your config is correct? For me it says that the one you posted here is faulty.
CSL Music Mod will also output errors into the Cities: Skylines log.
